### ISSUE TITLE
What for did you use Task.FromResult?

### ISSUE THREAD

**Issue by AliaksandrMakarchuk** [kardelw1409/WebBlog#1]
https://github.com/kardelw1409/WebBlog/blob/2774be3eb38fb4eb795579d480bc6d013b958d8c/WebBlog/WebBlog.ApplicationCore/Repositories/EntityRepository.cs#L47

**Comment by kardelw1409** [comment]
I still don't know multi thread programming well, but i thought all methods of repository should be async for better performance.

**Comment by AliaksandrMakarchuk** [comment]
Yes, it is good approach. I mean that _Task.FromResult_ is used in case when we need to return existing value from _async_ method.
In your code you do some work. Use _new Task(() => {})_ instead

**Comment by kardelw1409** [comment]
But method Get() must return IEnumerable, so we need Task.FromResult.

**Comment by AliaksandrMakarchuk** [comment]
Did you try to use this:
`return await new Task<IEnumerable<TEntity>>(() => dbContext.Set<TEntity>().Where(predicate));`

**Comment by kardelw1409** [comment]
Thanks, now I will know)

**Comment by kardelw1409** [comment]
Unfortunately, the method goes into endless waiting. In the debug work application is stopped after sql request.

**Comment by AliaksandrMakarchuk** [comment]
Use
`return await Task.Run(() => dbContext.Set<TEntity>().Where(predicate));`
instead

**Comment by kardelw1409** [comment]
It is worked
