### ISSUE TITLE
Extra view model?

### ISSUE THREAD

**Issue by AliaksandrMakarchuk** [kardelw1409/WebBlog#20]
https://github.com/kardelw1409/WebBlog/blob/0d15123fc41b93aaabbf73fdb9033736712b1c53/WebBlog/WebBlog.Web/Models/PostWithCommentsViewModel.cs#L9

What is the difference between this model and the _PostViewModel_? Why don't you use one view model for both with and without comments?

**Comment by kardelw1409** [comment]
Removed PostWithCommentsViewModel, made Post differently.
