### ISSUE TITLE
Ugly code

### ISSUE THREAD

**Issue by AliaksandrMakarchuk** [kardelw1409/WebBlog#21]
https://github.com/kardelw1409/WebBlog/blob/87ece89dbd4f0a40071c5bc16d8d6510391e83cf/WebBlog/WebBlog.Web/Controllers/PostsController.cs#L96

Why do we need to check _postView_ again? We already checked this a few rows before.

Please, fix all the places like this for all controllers if there are.

**Comment by kardelw1409** [comment]
The check is needed before isvalid to make an empty input (which is hidden by checked input and js) valid. Next, in the isvalid block, we also need this check, so as not to start loading from an empty input.
