### ISSUE TITLE
Whether exception is thrown if id is null?

### ISSUE THREAD

**Issue by AliaksandrMakarchuk** [kardelw1409/WebBlog#7]
https://github.com/kardelw1409/WebBlog/blob/2774be3eb38fb4eb795579d480bc6d013b958d8c/WebBlog/WebBlog.ApplicationCore/Repositories/EntityRepository.cs#L30

**Comment by kardelw1409** [comment]
Fixed FindById. If id equals null, throw NullReferenceException.
